### ISSUE TITLE
Control number of iterations / time in loom.tasks.infer?

### ISSUE THREAD

**Issue by fsaad** [posterior/loom#1]
Hello -- when running `loom.tasks.infer(NAME, sample_count=sample_count)` is it possible to specify the number of iterations / time to run inference? Looking at the `DEFAULTS` JSON in `config.py`, I cannot find an appropriate parameter. Thank you.

**Comment by fritzo** [comment]
Hi @fsaad, The parameter to control inference time is config['schedule']['extra_passes'] which defaults to 500. See https://github.com/posterior/loom/blob/master/loom/config.py#L39 This parameter ranges from 0 for single-pass streaming inference, to any large number. You can probably get good results with just 50.
